"""updated nulls fields

Revision ID: 1b1789f97a3e
Revises: f3c00ce6e46f
Create Date: 2023-05-28 15:28:41.455379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1789f97a3e'
down_revision = 'f3c00ce6e46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passageiro')
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('curso',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('turno',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.alter_column('turno',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('curso',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('passageiro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idAluno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cidadeOrigem', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cidadeDestino', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idAluno'], ['aluno.idPessoa'], name='passageiro_idAluno_fkey'),
    sa.PrimaryKeyConstraint('id', name='passageiro_pkey')
    )
    # ### end Alembic commands ###
