"""migrate inical

Revision ID: 481e837c2caf
Revises: 
Create Date: 2023-05-23 17:01:24.355391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481e837c2caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('idUf', sa.Integer(), nullable=True),
    sa.Column('idCidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCidade'], ['cidade.id'], ),
    sa.ForeignKeyConstraint(['idUf'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituto_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('idEndereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('idEndereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa')
    op.drop_table('instituto_ensino')
    op.drop_table('endereco')
    op.drop_table('uf')
    op.drop_table('cidade')
    # ### end Alembic commands ###
