"""removided idEndereco on pessoa

Revision ID: a80ace0b027f
Revises: d1bf520c0696
Create Date: 2023-05-28 16:56:13.466700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80ace0b027f'
down_revision = 'd1bf520c0696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_constraint('pessoa_idEndereco_fkey', type_='foreignkey')
        batch_op.drop_column('idEndereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idEndereco', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pessoa_idEndereco_fkey', 'endereco', ['idEndereco'], ['id'])

    # ### end Alembic commands ###
