"""adjusted relationship into pessoa and endereco

Revision ID: d1bf520c0696
Revises: 1b1789f97a3e
Create Date: 2023-05-28 16:53:09.224692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bf520c0696'
down_revision = '1b1789f97a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idAluno', sa.Integer(), nullable=True),
    sa.Column('cidadeOrigem', sa.String(), nullable=False),
    sa.Column('cidadeDestino', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idAluno'], ['aluno.idPessoa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idPessoa', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pessoa', ['idPessoa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idPessoa')

    op.drop_table('passageiro')
    # ### end Alembic commands ###
