"""adjusted relationship uf

Revision ID: e8ed3c5a3d18
Revises: 481e837c2caf
Create Date: 2023-05-25 13:48:48.810281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ed3c5a3d18'
down_revision = '481e837c2caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUf', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'uf', ['idUf'], ['id'])

    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_constraint('endereco_idUf_fkey', type_='foreignkey')
        batch_op.drop_column('idUf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUf', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('endereco_idUf_fkey', 'uf', ['idUf'], ['id'])

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idUf')

    # ### end Alembic commands ###
