"""initial migrate

Revision ID: f3c00ce6e46f
Revises: 
Create Date: 2023-05-27 21:42:42.981214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c00ce6e46f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('qtdPassageiros', sa.Integer(), nullable=False),
    sa.Column('tipoVeiculo', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('idUf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUf'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('idCidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCidade'], ['cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituicaoEnsino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('idEndereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('idEndereco', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('aluno',
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('idInstituicaoEnsino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idInstituicaoEnsino'], ['instituicaoEnsino.id'], ),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('idPessoa'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('funcionario',
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('idPessoa')
    )
    op.create_table('motorista',
    sa.Column('idFuncionario', sa.Integer(), nullable=False),
    sa.Column('idVeiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idFuncionario'], ['funcionario.idPessoa'], ),
    sa.ForeignKeyConstraint(['idVeiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('idFuncionario')
    )
    op.create_table('passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idAluno', sa.Integer(), nullable=True),
    sa.Column('cidadeOrigem', sa.String(), nullable=False),
    sa.Column('cidadeDestino', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idAluno'], ['aluno.idPessoa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefeitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretario', sa.Integer(), nullable=True),
    sa.Column('idEndereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['secretario'], ['funcionario.idPessoa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idMotorista', sa.Integer(), nullable=True),
    sa.Column('idVeiculo', sa.Integer(), nullable=True),
    sa.Column('idInstituicaoEnsino', sa.Integer(), nullable=True),
    sa.Column('idPrefeitura', sa.Integer(), nullable=True),
    sa.Column('cidadeOrigem', sa.String(), nullable=False),
    sa.Column('cidadeDestino', sa.String(), nullable=False),
    sa.Column('qdtAlunos', sa.Integer(), nullable=False),
    sa.Column('horarioSaida', sa.DateTime(), nullable=False),
    sa.Column('horarioChegada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idInstituicaoEnsino'], ['instituicaoEnsino.id'], ),
    sa.ForeignKeyConstraint(['idMotorista'], ['motorista.idFuncionario'], ),
    sa.ForeignKeyConstraint(['idPrefeitura'], ['prefeitura.id'], ),
    sa.ForeignKeyConstraint(['idVeiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota')
    op.drop_table('prefeitura')
    op.drop_table('passageiro')
    op.drop_table('motorista')
    op.drop_table('funcionario')
    op.drop_table('aluno')
    op.drop_table('pessoa')
    op.drop_table('instituicaoEnsino')
    op.drop_table('endereco')
    op.drop_table('cidade')
    op.drop_table('veiculo')
    op.drop_table('uf')
    # ### end Alembic commands ###
